#!/usr/bin/env python3
"""
kernel_explorer.py — Interactive kernel slice viewer.

Drag the q₀ and p₀ sliders to see how the RBF (stationary) and NKN
(nonstationary) kernels change shape at different base points.

Works in:
  - Jupyter notebook:  %matplotlib widget  then  run this file
  - Standalone:        python kernel_explorer.py   (uses plt.show())

Loads fitted kernel parameters from figures/kernel_params.json
(generated by experiment.py).
"""

import json, os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, RadioButtons

# ─── Load fitted kernel parameters ──────────────────────────────────────────

PARAM_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.', 'figures', 'kernel_params.json')
with open(PARAM_FILE) as f:
    params = json.load(f)

RBF_SF  = params['rbf']['sigma_f']
RBF_ELL = params['rbf']['ell']
NKN_M       = params['nkn']['M']
NKN_LOG_LAM = np.array(params['nkn']['log_lam'])
NKN_LOG_ELL = np.array(params['nkn']['log_ell'])
NKN_CENTERS = np.array(params['nkn']['centers'])
Q_RANGE = params['q_range']
P_RANGE = params['p_range']


# ─── Kernel evaluation functions ────────────────────────────────────────────

def rbf_kernel(z1, z2):
    d = z1 - z2
    return RBF_SF**2 * np.exp(-np.dot(d, d) / (2 * RBF_ELL**2))


def nkn_kernel(z1, z2):
    total = 0.0
    for i in range(NKN_M):
        lam = np.exp(NKN_LOG_LAM[i])
        ell = np.exp(NKN_LOG_ELL[i])
        c = NKN_CENTERS[i]
        u1 = (z1 - c) / ell
        u2 = (z2 - c) / ell
        phi1 = np.exp(-0.5 * np.dot(u1, u1))
        phi2 = np.exp(-0.5 * np.dot(u2, u2))
        total += lam * phi1 * phi2
    return total


# ─── Precompute grids ───────────────────────────────────────────────────────

N_PROFILE = 150
N_HEAT = 60
deltas = np.linspace(-2.0, 2.0, N_PROFILE)
heat_q = np.linspace(Q_RANGE[0], Q_RANGE[1], N_HEAT)
heat_p = np.linspace(P_RANGE[0], P_RANGE[1], N_HEAT)
TRANS = 1.0 / np.sqrt(3)   # elliptic-hyperbolic transition


def compute_profiles(q0, p0, mode):
    """1D profiles: k(base, base+δ) for both kernels."""
    rbf_vals = np.zeros(N_PROFILE)
    nkn_vals = np.zeros(N_PROFILE)
    z0 = np.array([q0, p0])
    for i, d in enumerate(deltas):
        z1 = np.array([q0 + d, p0]) if mode == 'q' else np.array([q0, p0 + d])
        rbf_vals[i] = rbf_kernel(z0, z1)
        nkn_vals[i] = nkn_kernel(z0, z1)
    return rbf_vals, nkn_vals


def compute_heatmap(q0, p0, mode):
    """2D heatmap: k(x, x') at fixed other coordinate."""
    pts = heat_q if mode == 'q' else heat_p
    fix = p0 if mode == 'q' else q0
    n = len(pts)
    nkn_grid = np.zeros((n, n))
    for i in range(n):
        z_i = np.array([pts[i], fix]) if mode == 'q' else np.array([fix, pts[i]])
        for j in range(n):
            z_j = np.array([pts[j], fix]) if mode == 'q' else np.array([fix, pts[j]])
            nkn_grid[i, j] = nkn_kernel(z_i, z_j)
    return pts, nkn_grid


# ─── Build the figure ───────────────────────────────────────────────────────

fig = plt.figure(figsize=(14, 9))
fig.suptitle('Interactive Kernel Explorer: RBF (stationary) vs NKN (nonstationary)',
             fontsize=14, y=0.98)

# Layout: top row = 1D profiles, bottom row = 2D heatmap + info
ax_rbf  = fig.add_axes([0.06, 0.52, 0.40, 0.38])   # RBF 1D profile
ax_nkn  = fig.add_axes([0.54, 0.52, 0.40, 0.38])   # NKN 1D profile
ax_heat = fig.add_axes([0.06, 0.12, 0.35, 0.32])    # NKN 2D heatmap
ax_info = fig.add_axes([0.50, 0.12, 0.44, 0.32])    # info panel

# Sliders
ax_q0   = fig.add_axes([0.15, 0.04, 0.30, 0.025])
ax_p0   = fig.add_axes([0.15, 0.01, 0.30, 0.025])
ax_mode = fig.add_axes([0.60, 0.01, 0.12, 0.06])

slider_q0 = Slider(ax_q0, 'q₀', Q_RANGE[0], Q_RANGE[1], valinit=0.0, valstep=0.02)
slider_p0 = Slider(ax_p0, 'p₀', P_RANGE[0], P_RANGE[1], valinit=0.0, valstep=0.02)
radio_mode = RadioButtons(ax_mode, ('q slice', 'p slice'), active=0)

# Initial computation
mode = 'q'
q0, p0 = 0.0, 0.0
rbf_vals, nkn_vals = compute_profiles(q0, p0, mode)
pts_h, nkn_heat = compute_heatmap(q0, p0, mode)

# Plot initial profiles
[line_rbf] = ax_rbf.plot(deltas, rbf_vals, 'C1', lw=2.5)
ax_rbf.set_title('RBF: k(base, base+δ)', fontsize=12)
ax_rbf.set_xlabel('δ'); ax_rbf.set_ylabel('k')
ax_rbf.grid(alpha=0.3)
vline_rbf1 = ax_rbf.axvline(0, color='gray', ls=':', lw=0.8)

[line_nkn] = ax_nkn.plot(deltas, nkn_vals, 'C0', lw=2.5)
ax_nkn.set_title('NKN: k(base, base+δ)', fontsize=12)
ax_nkn.set_xlabel('δ'); ax_nkn.set_ylabel('k')
ax_nkn.grid(alpha=0.3)
vline_nkn1 = ax_nkn.axvline(0, color='gray', ls=':', lw=0.8)
# Transition lines
vline_nkn_t1 = ax_nkn.axvline(-TRANS - q0, color='red', ls='--', lw=0.8, alpha=0.4)
vline_nkn_t2 = ax_nkn.axvline(TRANS - q0, color='red', ls='--', lw=0.8, alpha=0.4)

# 2D heatmap
im_heat = ax_heat.imshow(nkn_heat, origin='lower', aspect='auto',
                          extent=[pts_h[0], pts_h[-1], pts_h[0], pts_h[-1]],
                          cmap='viridis')
heat_title = ax_heat.set_title(f'NKN k(q, q\') at p₀={p0:.2f}', fontsize=11)
ax_heat.set_xlabel('q' if mode == 'q' else 'p')
ax_heat.set_ylabel("q'" if mode == 'q' else "p'")
# Transition lines on heatmap
hline1 = ax_heat.axhline(-TRANS, color='red', ls='--', lw=0.8, alpha=0.4)
hline2 = ax_heat.axhline(TRANS, color='red', ls='--', lw=0.8, alpha=0.4)
vlineh1 = ax_heat.axvline(-TRANS, color='red', ls='--', lw=0.8, alpha=0.4)
vlineh2 = ax_heat.axvline(TRANS, color='red', ls='--', lw=0.8, alpha=0.4)
dot_heat = ax_heat.plot(q0, q0, 'w+', ms=12, mew=2)[0]

# Info panel
ax_info.axis('off')
info_text = ax_info.text(0.05, 0.95, '', transform=ax_info.transAxes,
                         fontsize=11, verticalalignment='top',
                         fontfamily='monospace',
                         bbox=dict(boxstyle='round', facecolor='lightyellow',
                                   alpha=0.8))


def update(val=None):
    global mode
    q0 = slider_q0.val
    p0 = slider_p0.val
    mode = 'q' if radio_mode.value_selected == 'q slice' else 'p'

    # Recompute profiles
    rbf_v, nkn_v = compute_profiles(q0, p0, mode)
    line_rbf.set_ydata(rbf_v)
    line_nkn.set_ydata(nkn_v)

    # Rescale y-axes
    rbf_max = max(rbf_v.max(), 1e-10)
    nkn_max = max(nkn_v.max(), 1e-10)
    ax_rbf.set_ylim(-0.05 * rbf_max, 1.1 * rbf_max)
    ax_nkn.set_ylim(-0.05 * nkn_max, 1.1 * nkn_max)

    # Update transition lines on NKN profile
    if mode == 'q':
        vline_nkn_t1.set_xdata([-TRANS - q0])
        vline_nkn_t2.set_xdata([TRANS - q0])
        vline_nkn_t1.set_visible(True)
        vline_nkn_t2.set_visible(True)
    else:
        vline_nkn_t1.set_visible(False)
        vline_nkn_t2.set_visible(False)

    # Recompute heatmap
    pts_h, nkn_h = compute_heatmap(q0, p0, mode)
    im_heat.set_data(nkn_h)
    im_heat.set_extent([pts_h[0], pts_h[-1], pts_h[0], pts_h[-1]])
    im_heat.set_clim(vmin=nkn_h.min(), vmax=max(nkn_h.max(), 1e-10))

    lbl = 'q' if mode == 'q' else 'p'
    fix_lbl = f'p₀={p0:.2f}' if mode == 'q' else f'q₀={q0:.2f}'
    ax_heat.set_xlabel(lbl)
    ax_heat.set_ylabel(f"{lbl}'")
    heat_title.set_text(f"NKN k({lbl}, {lbl}') at {fix_lbl}")

    base = q0 if mode == 'q' else p0
    dot_heat.set_data([base], [base])

    # Show/hide transition lines on heatmap
    for ln in [hline1, hline2, vlineh1, vlineh2]:
        ln.set_visible(mode == 'q')

    # Profile titles
    ax_rbf.set_title(f'RBF: k({lbl}₀, {lbl}₀+δ) at {fix_lbl}', fontsize=12)
    ax_nkn.set_title(f'NKN: k({lbl}₀, {lbl}₀+δ) at {fix_lbl}', fontsize=12)

    # Info text
    lyap = np.sqrt(max(0, 1 - 3*q0**2))
    noise = (1 - 3*q0**2)**2
    region = 'HYPERBOLIC (near separatrix)' if abs(q0) < TRANS else 'ELLIPTIC (inside well)'
    k_nkn_diag = nkn_kernel(np.array([q0, p0]), np.array([q0, p0]))
    k_rbf_diag = rbf_kernel(np.array([q0, p0]), np.array([q0, p0]))

    info_text.set_text(
        f'Base point:  (q₀, p₀) = ({q0:.2f}, {p0:.2f})\n'
        f'Region:      {region}\n'
        f'λ_max(q₀):   {lyap:.4f}\n'
        f'(1−3q²)²:    {noise:.4f}  (true noise scaling)\n'
        f'\n'
        f'RBF k(z₀,z₀) = {k_rbf_diag:.2f}  (constant everywhere)\n'
        f'NKN k(z₀,z₀) = {k_nkn_diag:.4f}  (position-dependent)\n'
        f'\n'
        f'NKN peak:     {nkn_v.max():.4f}\n'
        f'NKN width:    {np.ptp(deltas[nkn_v > 0.5*nkn_v.max()]):.3f}  (FWHM)\n'
        f'RBF peak:     {rbf_v.max():.2f}  (same everywhere)'
    )

    fig.canvas.draw_idle()


# Connect callbacks
slider_q0.on_changed(update)
slider_p0.on_changed(update)
radio_mode.on_clicked(update)

# Initial draw
update()

plt.show()
